data:
  version: "small"
  locale: "us"
  sample_frac: null

experiments:
  - name: "1. Baseline (MiniLM-L6)"
    pipeline:
      embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
      index_type: "flat"
      use_reranker: false
      text_strategy: "basic"
  
  - name: "2. MiniLM-L6 + IVF"
    pipeline:
      embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
      index_type: "ivf"
      use_reranker: false
      text_strategy: "basic"
  
  - name: "3. MiniLM-L6 + Reranker"
    pipeline:
      embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
      index_type: "ivf"
      use_reranker: true
      reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
      text_strategy: "basic"
  
  - name: "4. MiniLM-L6 + Enhanced Text"
    pipeline:
      embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
      index_type: "ivf"
      use_reranker: false
      text_strategy: "enhanced"
  
  - name: "5. MiniLM-L6 + Enhanced + Reranker"
    pipeline:
      embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
      index_type: "ivf"
      use_reranker: true
      reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
      text_strategy: "enhanced"
  
  - name: "6. QA-MiniLM + Enhanced + Reranker"
    pipeline:
      embedding_model: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
      index_type: "ivf"
      use_reranker: true
      reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
      text_strategy: "enhanced"
  
  - name: "7. MiniLM-L12 + Enhanced + Reranker"
    pipeline:
      embedding_model: "sentence-transformers/all-MiniLM-L12-v2"
      index_type: "ivf"
      use_reranker: true
      reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
      text_strategy: "enhanced"